---
- name: Prepare Edge Cluster
  hosts: localhost
  become: true
  gather_facts: no
  vars_files:
    - variables.yaml

  tasks:
    - name: Update apt repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Azure CLI
      ansible.builtin.shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Add Azure CLI extensions
      ansible.builtin.shell: |
        az extension add --upgrade --name connectedk8s
        az extension add --upgrade --name azure-iot-ops

    - name: Install K3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable traefik" sh -

    - name: Create .kube directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: Configure K3s
      ansible.builtin.shell: |
        sudo KUBECONFIG=~/.kube/config:/etc/rancher/k3s/k3s.yaml kubectl config view --flatten > ~/.kube/merged
        mv ~/.kube/merged ~/.kube/config
        chmod 0600 ~/.kube/config
        export KUBECONFIG=~/.kube/config
        kubectl config use-context default

    - name: Set fs.inotify.max_user_instances
      ansible.posix.sysctl:
        name: fs.inotify.max_user_instances
        value: '8192'
        sysctl_set: yes
        state: present

    - name: Set fs.inotify.max_user_watches
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        sysctl_set: yes
        state: present

    - name: Set fs.file-max
      ansible.posix.sysctl:
        name: fs.file-max
        value: '100000'
        sysctl_set: yes
        state: present