---
- name: Configure Azure IoT Operations
  hosts: localhost
  become: true
  gather_facts: no
  vars_files:
    - variables.yaml

  tasks:
    - name: Authorize Azure IoT Operations to send messages to Event Hub
      ansible.builtin.shell: |
        AZ_AIO_EXT=$(az k8s-extension list --cluster-name "{{ AIO_CLUSTER_NAME }}" --resource-group "{{ RESOURCE_GROUP }}" --cluster-type connectedClusters --query "[?extensionType=='microsoft.iotoperations'].identity.principalId" --output tsv)
        az role assignment create --assignee $AZ_AIO_EXT --role "Azure Event Hubs Data Sender" --scope "{{ EVENTHUB_ID }}"

    - name: Download the Distributed State Store tool
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/dss/dss_set
        dest: /tmp/dss_set
        mode: '0755'

    - name: Download the Operators Dataset
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/dss/operators.json
        dest: /tmp/operators.json

    - name: Download the Products Dataset
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/dss/products.json
        dest: /tmp/products.json

    - name: Download the data flow
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/silver-to-cloud.yaml
        dest: /tmp/silver-to-cloud.yaml

    - name: Modify file with the name of the event hub namespace
      ansible.builtin.replace:
        path: /tmp/silver-to-cloud.yaml
        regexp: '<EVENTHUB_NAMESPACE>'
        replace: "{{ EVENTHUB_NAMESPACE }}"

    - name: Modify file with the name of the event hub name
      ansible.builtin.replace:
        path: /tmp/silver-to-cloud.yaml
        regexp: '<EVENTHUB>'
        replace: "{{ EVENTHUB_NAME }}"

    - name: Import the operators dataset in the Distributed State Store
      ansible.builtin.shell: /tmp/dss_set --key operators --file "operators.json" --address localhost

    - name: Import the products dataset in the Distributed State Store
      ansible.builtin.shell: /tmp/dss_set --key products --file "products.json" --address localhost

    - name: Deploy Factory Simulator - configuration
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/k3s/pods/simulator/configuration.yaml

    - name: Deploy Factory Simulator - deployment
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/k3s/pods/simulator/deployment.yaml

    - name: Deploy Factory Simulator - bronze to silver
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/bronze-to-silver.yaml

    - name: Deploy the Cloud connector to Azure Event Hub
      ansible.builtin.shell: kubectl apply -f /tmp/silver-to-cloud.yaml