---
- name: Unprovision Edge Resources
  hosts: localhost
  become: true
  gather_facts: no
  vars_files:
    - variables.yaml

  tasks:
    - name: Connect to Azure subscription
      ansible.builtin.shell: |
        az login --service-principal --username "{{ AIO_SP_APPID }}" --password="{{ AIO_SP_SECRET }}" --tenant "{{ TENANT }}"
        az account set --subscription "{{ SUBSCRIPTION_ID }}"

    - name: Delete the Data Flow 'Cloud Connector to Azure Event Hub'
      ansible.builtin.shell: kubectl delete -f /tmp/silver-to-cloud.yaml

    - name: Delete the Data Flow 'bronze to silver'
      ansible.builtin.shell: kubectl delete -f https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/bronze-to-silver.yaml

    - name: Delete Factory MQTT Simulator - Deployment
      ansible.builtin.shell: kubectl delete -f https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/k3s/pods/simulator/deployment.yaml

    - name: Delete Factory MQTT Simulator - Configuration
      ansible.builtin.shell: kubectl delete -f https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/k3s/pods/simulator/configuration.yaml

    - name: Delete Azure IoT Operations
      ansible.builtin.shell: az iot ops delete --yes --name "{{ AIO_CLUSTER_NAME }}"-aio --resource-group "{{ RESOURCE_GROUP }}" --include-deps

    - name: Delete Azure Arc Connected Cluster
      ansible.builtin.shell: az connectedk8s delete --yes --name "{{ AIO_CLUSTER_NAME }}" --resource-group "{{ RESOURCE_GROUP }}"

    - name: Uninstall Kubernetes (K3s)
      ansible.builtin.shell: |
        /usr/local/bin/k3s-uninstall.sh