- name: Deploy Edge Resources
  hosts: localhost
  become: true
  gather_facts: no
  vars_files:
    - variables_edge.yaml

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: curl
        state: present

    - name: Install Azure CLI
      shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Add Azure CLI extensions
      shell: |
        az extension add --upgrade --name connectedk8s
        az extension add --upgrade --name azure-iot-ops

    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable traefik" sh -

    - name: Create .kube directory
      file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: Configure K3s
      shell: |
        sudo KUBECONFIG=~/.kube/config:/etc/rancher/k3s/k3s.yaml kubectl config view --flatten > ~/.kube/merged
        mv ~/.kube/merged ~/.kube/config
        chmod 0600 ~/.kube/config
        export KUBECONFIG=~/.kube/config
        kubectl config use-context default

    - name: Set fs.inotify.max_user_instances
      sysctl:
        name: fs.inotify.max_user_instances
        value: '8192'
        sysctl_set: yes
        state: present

    - name: Set fs.inotify.max_user_watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        sysctl_set: yes
        state: present

    - name: Set fs.file-max
      sysctl:
        name: fs.file-max
        value: '100000'
        sysctl_set: yes
        state: present

    - name: Check Azure IoT Operations prerequisites
      shell: az iot ops check

    - name: Connecting Edge cluster to Azure Arc
      shell: >
        az connectedk8s connect --name {{ AIO_CLUSTER_NAME }} --location {{ LOCATION }} --resource-group {{ RESOURCE_GROUP }} --subscription {{ SUBSCRIPTION_ID }} --enable-oidc-issuer --enable-workload-identity --disable-auto-upgrade

    - name: Configuring Arc custom location
      shell: >
        az connectedk8s enable-features --name {{ AIO_CLUSTER_NAME }} --resource-group {{ RESOURCE_GROUP }} --custom-locations-oid {{ ARC_OBJECT_ID }} --features cluster-connect custom-locations
      register: az_arc_enable_cl

    - name: Retrieve OIDC Issuer Profile
      shell: >
        az connectedk8s show --resource-group {{ RESOURCE_GROUP }} --name {{ AIO_CLUSTER_NAME }} --query oidcIssuerProfile.issuerUrl --output tsv
      register: oidc_issuer_profile

    - name: Configure K3s
      shell: |
        sudo touch /etc/rancher/k3s/config.yaml
        sudo bash -c 'cat <<EOL > /etc/rancher/k3s/config.yaml
        kube-apiserver-arg:
         - service-account-issuer={{ oidc_issuer_profile.stdout }}
         - service-account-max-token-expiration=24h
        EOL'
        sudo systemctl restart k3s

    - name: Initialize Azure IoT Operations foundations installation
      shell: >
        az iot ops init --subscription {{ SUBSCRIPTION_ID }} --cluster {{ AIO_CLUSTER_NAME }} --resource-group {{ RESOURCE_GROUP }}

    - name: Install Azure IoT Operations
      shell: >
        az iot ops create --add-insecure-listener --kubernetes-distro K3s --name {{ AIO_CLUSTER_NAME }}-ops-instance --cluster {{ AIO_CLUSTER_NAME }} --resource-group {{ RESOURCE_GROUP }} --sr-resource-id {{ SCHEMA_REGISTRY_ID }} --broker-frontend-replicas 1 --broker-frontend-workers 1 --broker-backend-part 1 --broker-backend-workers 1 --broker-backend-rf 2 --broker-mem-profile Low

    - name: Enable secret sync
      shell: >
        az iot ops secretsync enable --instance {{ AIO_CLUSTER_NAME }}-ops-instance --resource-group {{ RESOURCE_GROUP }} --mi-user-assigned {{ AIO_MANAGED_IDENTITY_SECRETS_ID }} --kv-resource-id {{ KEYVAULT_ID }}

    - name: Enable cloud connections sync
      shell: >
        az iot ops identity assign --name {{ AIO_CLUSTER_NAME }}-ops-instance --resource-group {{ RESOURCE_GROUP }} --mi-user-assigned {{ AIO_MANAGED_IDENTITY_COMPONENTS_ID }}

    - name: Authorize Azure IoT Operations to send messages to Event Hub
      shell: |
        AZ_AIO_EXT=$(az k8s-extension list --cluster-name {{ AIO_CLUSTER_NAME }} --resource-group {{ RESOURCE_GROUP }} --cluster-type connectedClusters --query "[?extensionType=='microsoft.iotoperations'].identity.principalId" --output tsv)
        az role assignment create --assignee $AZ_AIO_EXT --role "Azure Event Hubs Data Sender" --scope {{ EVENTHUB_ID }}

    - name: Download the Distributed State Store tool
      get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/dss/dss_set
        dest: ./dss_set
        mode: '0755'

    - name: Download the Operators Dataset
      get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/dss/operators.json
        dest: ./operators.json

    - name: Download the Products Dataset
      get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/dss/products.json
        dest: ./products.json

    - name: Download the data flow
      get_url:
        url: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/silver-to-cloud.yaml
        dest: ./silver-to-cloud.yaml

    - name: Modify file with the name of the event hub namespace
      replace:
        path: ./silver-to-cloud.yaml
        regexp: '<EVENTHUB_NAMESPACE>'
        replace: "{{ EVENTHUB_NAMESPACE }}"

    - name: Modify file with the name of the event hub name
      replace:
        path: ./silver-to-cloud.yaml
        regexp: '<EVENTHUB>'
        replace: "{{ EVENTHUB_NAME }}"

    - name: Import the operators dataset in the Distributed State Store
      shell: ./dss_set --key operators --file "operators.json" --address localhost

    - name: Import the products dataset in the Distributed State Store
      shell: ./dss_set --key products --file "products.json" --address localhost

    - name: Deploy Factory Simulator - configuration
      kubectl:
        state: present
        definition: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/k3s/pods/simulator/configuration.yaml

    - name: Deploy Factory Simulator - deployment
      kubectl:
        state: present
        definition: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/k3s/pods/simulator/deployment.yaml

    - name: Deploy Factory Simulator - bronze to silver
      kubectl:
        state: present
        definition: https://raw.githubusercontent.com/chriscrcodes/talk-to-your-factory/main/artifacts/templates/azure-iot-operations/dataflows/bronze-to-silver.yaml

    - name: Deploy the cloud connector
      kubectl:
        state: present
        definition: ./silver-to-cloud.yaml