apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azure-iot-operations
  name: iiot-simulator-factory
  labels:
    app: iiot-simulator-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iiot-simulator-factory
  template:
    metadata:
      labels:
        app: iiot-simulator-factory
    spec:
      containers:
        - name: iiot-simulator-factory
          image: ghcr.io/azure-samples/explore-iot-operations/industrial-data-simulator:latest
          imagePullPolicy: Always
          ports:
          - name: prometheus
            containerPort: 2114
          resources:
            requests:
              memory: "128Mi"
              cpu: "1000m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          command:
            - "./bin/industrial-data-simulator"
            - "--stdin=false"
            - "--config=/etc/data-simulator/config.yml"
          volumeMounts:
            - mountPath: /etc/data-simulator/config.yml
              subPath: config.yml
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: iiot-simulator-factory-conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: azure-iot-operations
  name: simulator-svc-prom
  labels:
    app: iiot-simulator-factory
spec:
  ports:
  - port: 2114
    name: prometheus
  type: ClusterIP
  selector:
    app: iiot-simulator-factory
---
apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: iiot-simulator-factory-listener
  namespace: azure-iot-operations
spec:
  authenticationEnabled: false
  authorizationEnabled: false
  brokerRef: broker
  port: 1883
  serviceName: aio-mq-dmqtt-frontend
  serviceType: clusterIp