apiVersion: v1
kind: ConfigMap
metadata:
  namespace: azure-iot-operations
  name: iiot-simulator-mes-conf
data:
  config.yml: |-
    logger:
      level: 0
    servers:
      http:
        port: 3333
        resources:
          - path: /maintenanceData
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              [
                {
                  "Cell": "7H27L4",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "SDL4OYV5"
                },
                {
                  "Cell": "LP0HNU",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "KXN5WJG5"
                },
                {
                  "Cell": "X78TFV",
                  "MaintenanceStatus": "Overdue",
                  "SerialNumber": "ZDCJ35BB"
                },
                {
                  "Cell": "07RIRW",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "JWS7BIH8"
                },
                {
                  "Cell": "NVIIRV",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "HHXW9A9C"
                },
                {
                  "Cell": "834C8X",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "4CLC29B9"
                },
                {
                  "Cell": "IMHAO0",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "ET9NLL3C"
                },
                {
                  "Cell": "EJAOET",
                  "MaintenanceStatus": "Overdue",
                  "SerialNumber": "IZVN2FKH"
                },
                {
                  "Cell": "MI9VEP",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "NBY997MH"
                },
                {
                  "Cell": "BI2BI0",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "J9WA8QJF"
                },
                {
                  "Cell": "53FCIU",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "49EIQXR"
                },
                {
                  "Cell": "0CYBFQ",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "YFXFW2PP"
                },
                {
                  "Cell": "0DKBDE",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "AFKFW3PD"
                },
                {
                  "Cell": "LFR8PP",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "TT2W87EV"
                },
                {
                  "Cell": "DR2FB3",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "TXI5GVBL"
                },
                {
                  "Cell": "PIBIDT",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "OFPAYVJV"
                },
                {
                  "Cell": "I1IX2I",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "14MF5WGL"
                },
                {
                  "Cell": "48H0LP",
                  "MaintenanceStatus": "Overdue",
                  "SerialNumber": "G479VVF3"
                },
                {
                  "Cell": "82TFFU",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "XWJU57IY"
                },
                {
                  "Cell": "9OMOSD",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "X5KRYSV1"
                },
                {
                  "Cell": "9VR7RO",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "6M9HPI0F"
                },
                {
                  "Cell": "JKTB4G",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "MT0G03RP"
                },
                {
                  "Cell": "SDZI4E",
                  "MaintenanceStatus": "Overdue",
                  "SerialNumber": "KXQ5UR9D"
                },
                {
                  "Cell": "MHB89D",
                  "MaintenanceStatus": "Upcoming",
                  "SerialNumber": "4VKV412K"
                },
                {
                  "Cell": "RZ8BO8",
                  "MaintenanceStatus": "Done",
                  "SerialNumber": "8UXUWE53"
                }
              ]
          - path: /productionData
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              [
                {
                  "Cell": "7H27L4",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "LP0HNU",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "X78TFV",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "07RIRW",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "NVIIRV",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "834C8X",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "IMHAO0",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "EJAOET",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "MI9VEP",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "BI2BI0",
                  "Product":"Car Model 1",
                  "Shift":0
                },
                {
                  "Cell": "53FCIU",
                  "Product":"Battery Model 1",
                  "Shift":1
                },
                {
                  "Cell": "0CYBFQ",
                  "Product":"Battery Model 1",
                  "Shift":1
                },
                {
                  "Cell": "0DKBDE",
                  "Product":"Battery Model 1",
                  "Shift":1
                },
                {
                  "Cell": "LFR8PP",
                  "Product":"Battery Model 1",
                  "Shift":1
                },
                {
                  "Cell": "DR2FB3",
                  "Product":"Battery Model 1",
                  "Shift":1
                },
                {
                  "Cell": "PIBIDT",
                  "Product":"Car Model 2",
                  "Shift":2
                },
                {
                  "Cell": "I1IX2I",
                  "Product":"Car Model 2",
                  "Shift":2
                },
                {
                  "Cell": "48H0LP",
                  "Product":"Car Model 2",
                  "Shift":2
                },
                {
                  "Cell": "82TFFU",
                  "Product":"Car Model 2",
                  "Shift":2
                },
                {
                  "Cell": "9OMOSD",
                  "Product":"Car Model 2",
                  "Shift":2
                },
                {
                  "Cell": "9VR7RO",
                  "Product":"Truck Model 1",
                  "Shift":3
                },
                {
                  "Cell": "JKTB4G",
                  "Product":"Truck Model 1",
                  "Shift":3
                },
                {
                  "Cell": "SDZI4E",
                  "Product":"Truck Model 1",
                  "Shift":3
                },
                {
                  "Cell": "MHB89D",
                  "Product":"Truck Model 1",
                  "Shift":3
                },
                {
                  "Cell": "RZ8BO8",
                  "Product":"Truck Model 1",
                  "Shift":3
                }
              ]
          - path: /operatorData
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              [
                  {
                      "Shift":0,
                      "Operator":"Steve",
                      "PerformanceTarget":45,
                      "PackagedProductTarget":12960
                  },
                  {
                      "Shift":1,
                      "Operator":"Lisa",
                      "PerformanceTarget":60,
                      "PackagedProductTarget":17280
                  },
                  {
                      "Shift":2,
                      "Operator":"Tom",
                      "PerformanceTarget":50,
                      "PackagedProductTarget":14400
                  },
                  {
                      "Shift":3,
                      "Operator":"Jane",
                      "PerformanceTarget":50,
                      "PackagedProductTarget":14400
                  }
              ]
      grpc:
        port: 3334
        outputs: ["output1"]
    outputs:
      - name: output1
        type: stdout