apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: bronze-to-silver
  namespace: azure-iot-operations
spec:
  profileRef: default
  mode: Enabled
  operations:
    - operationType: Source
      sourceSettings:
        endpointRef: default
        dataSources:
        - LightningCars/# # <TOPIC>
    - operationType: BuiltInTransformation
      builtInTransformationSettings:
        map:
          - inputs:
              - '*'
            output: '*'
          - inputs:
              - '$context(products).ProductId'
            output: ProductId
          - inputs:
              - '$context(operators).Hours'
            output: ShiftHours
          - inputs:
              - '$context(operators).EmployeeId'
            output: EmployeeId
        datasets:
         - key: products
           inputs:
             - '$source.Cell'               # - $1
             - '$context(products).Cell'    # - $2
           expression: '$1 == $2'
         - key: operators
           inputs:
             - '$source.Shift'              # - $1
             - '$context(operators).Shift'  # - $2
           expression: '$1 == $2'
    - operationType: Destination
      destinationSettings:
        endpointRef: default
        dataDestination: Silver