apiVersion: connectivity.iotoperations.azure.com/v1
kind: DataflowEndpoint
metadata:
  name: azure-eventhub
  namespace: azure-iot-operations
spec:
  endpointType: Kafka
  kafkaSettings:
    host: '<EVENTHUB_NAMESPACE>.servicebus.windows.net:9093'
    batching:
      latencyMs: 0
      maxMessages: 100
    tls:
      mode: Enabled
    authentication:
      method: SystemAssignedManagedIdentity
      systemAssignedManagedIdentitySettings:
        audience: https://<EVENTHUB_NAMESPACE>.servicebus.windows.net
---
apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: silver-to-cloud
  namespace: azure-iot-operations
spec:
  profileRef: default
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: default
        dataSources:
        - Silver/#
    - operationType: destination
      destinationSettings:
        endpointRef: azure-eventhub
        dataDestination: <EVENTHUB>